[project]
name = "usg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "thefuzz>=0.22.1",
    "typer>=0.27.2",
]

[project.scripts]
usg = "usg:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
